import io
from odoo import api, models

try:
    import xlsxwriter
except ImportError:  # xlsxwriter is an Odoo dependency in normal deployments
    xlsxwriter = None


class StockAnalyticsExcelReport(models.AbstractModel):
    _name = 'report.stock_advanced_analytics.stock_excel_report'
    _description = 'Inventory Analytics Excel Report'

    @api.model
    def generate_xlsx(self, wizard):
        if xlsxwriter is None:
            raise ImportError('xlsxwriter is required to generate Inventory Analytics Excel reports.')
        payload = wizard.get_report_payload()
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True})
        formats = self._formats(workbook)
        self.write_metadata(workbook, payload, formats)
        for section_name, rows in payload.get('sections', {}).items():
            self.write_table(workbook, section_name, rows, formats)
        workbook.close(); output.seek(0)
        return output.read()

    def _formats(self, workbook):
        return {
            'title': workbook.add_format({'bold': True, 'font_size': 14, 'bg_color': '#1f4e78', 'font_color': 'white'}),
            'header': workbook.add_format({'bold': True, 'bg_color': '#d9eaf7', 'border': 1}),
            'text': workbook.add_format({'border': 1}),
            'quantity': workbook.add_format({'border': 1, 'num_format': '#,##0.00'}),
            'integer': workbook.add_format({'border': 1, 'num_format': '#,##0'}),
            'date': workbook.add_format({'border': 1, 'num_format': 'yyyy-mm-dd'}),
            'datetime': workbook.add_format({'border': 1, 'num_format': 'yyyy-mm-dd hh:mm'}),
            'total': workbook.add_format({'bold': True, 'border': 1, 'bg_color': '#e2f0d9', 'num_format': '#,##0.00'}),
            'warning': workbook.add_format({'bg_color': '#ffc7ce'}),
        }

    def write_metadata(self, workbook, payload, formats):
        sheet = workbook.add_worksheet('Summary')
        meta = payload.get('metadata', {})
        sheet.write(0, 0, 'Inventory Advanced Analytics', formats['title'])
        items = [('Report Type', payload.get('report_type')), ('Company', meta.get('company')), ('Generated By', meta.get('generated_by')), ('Generated Datetime', meta.get('generated_at')), ('Timezone', meta.get('timezone'))]
        for idx, (label, value) in enumerate(items, start=2):
            sheet.write(idx, 0, label, formats['header']); sheet.write(idx, 1, str(value or ''), formats['text'])
        sheet.write(8, 0, 'Filters', formats['header']); sheet.write(8, 1, str(meta.get('filters', {})), formats['text'])
        sheet.set_column(0, 0, 24); sheet.set_column(1, 1, 80); sheet.freeze_panes(2, 0)

    def write_table(self, workbook, sheet_name, rows, formats):
        safe_name = self._safe_sheet_name(sheet_name)
        if safe_name in [s.get_name() for s in workbook.worksheets()]:
            safe_name = safe_name[:26] + '_' + str(len(workbook.worksheets()))
        sheet = workbook.add_worksheet(safe_name)
        rows = rows if isinstance(rows, list) else [rows]
        if not rows:
            sheet.write(0, 0, sheet_name, formats['title']); sheet.write(2, 0, 'No data for selected filters.', formats['text']); return
        headers = list(rows[0].keys()) if isinstance(rows[0], dict) else ['value']
        sheet.write(0, 0, sheet_name, formats['title'])
        for col, header in enumerate(headers): sheet.write(2, col, header, formats['header'])
        for r, row in enumerate(rows, start=3):
            row = row if isinstance(row, dict) else {'value': row}
            for c, header in enumerate(headers): sheet.write(r, c, row.get(header, ''), self.get_format_for_column(header, formats))
        self.write_totals_row(sheet, rows, headers, formats, start_row=3)
        sheet.autofilter(2, 0, 2 + len(rows), max(len(headers)-1, 0)); sheet.freeze_panes(3, 0)
        self.auto_width_columns(sheet, rows, headers); self.apply_conditional_formatting(sheet, rows, headers, formats, 3)

    def auto_width_columns(self, sheet, rows, headers):
        for c, header in enumerate(headers):
            width = min(max(len(str(header)) + 2, *(len(str((row if isinstance(row, dict) else {'value': row}).get(header, ''))) + 2 for row in rows[:200])), 60)
            sheet.set_column(c, c, width)

    def get_format_for_column(self, column, formats):
        name = column.lower()
        if any(token in name for token in ['quantity','qty','requested_qty','done_qty','pending_qty','incoming','outgoing','opening','closing','balance','available','reserved']): return formats['quantity']
        if any(token in name for token in ['count','transfers','requests','receipts','product_count','movement_count']): return formats['integer']
        if 'datetime' in name or 'generated_at' in name: return formats['datetime']
        if 'date' in name: return formats['date']
        return formats['text']

    def write_totals_row(self, sheet, rows, headers, formats, start_row=3):
        row_idx = start_row + len(rows)
        sheet.write(row_idx, 0, 'Totals', formats['total'])
        for col, header in enumerate(headers[1:], start=1):
            if self.get_format_for_column(header, formats) in (formats['quantity'], formats['integer']):
                sheet.write_formula(row_idx, col, f'=SUM({xlsxwriter.utility.xl_col_to_name(col)}{start_row+1}:{xlsxwriter.utility.xl_col_to_name(col)}{row_idx})', formats['total'])

    def apply_conditional_formatting(self, sheet, rows, headers, formats, start_row):
        for col, header in enumerate(headers):
            if 'difference' in header.lower() or 'negative' in header.lower():
                sheet.conditional_format(start_row, col, start_row + len(rows), col, {'type': 'cell', 'criteria': '<', 'value': 0, 'format': formats['warning']})

    def _safe_sheet_name(self, name):
        for ch in '[]:*?/\\': name = name.replace(ch, ' ')
        return (name or 'Sheet')[:31]
